FORMS_TEMPLATES = [
    {'name': 'Entering Form',
     "email": 'email',
     "phone": 'phone',
     "date": 'date',
     "text": 'text',},

    {'name': 'Three Fields Form - Email & Date & Text',
     'email': 'email',
     "datetime": 'date',
     "message": 'text',},
    {'name': 'Three Fields Form - Phone & Date & Text',
     "num": 'phone',
     "birthday": 'date',
     "notification": 'text',},

    {'name': 'Two Fields Form - Phone & Date',
     "field_number": 'phone',
     "field_date": 'date'},
    {'name': 'Two Fields Form - Email & Date',
     "user": 'email',
     "order_date": 'date'},
    {'name': 'Two Fields Form - Text & Phone',
     "user": 'phone',
     "text": 'text'},

    {'name': 'Email Form',
     "email": 'email',},
    {'name': 'Phone Form',
     "user": 'phone',},
    {'name': 'Date Form',
     "birthday": 'date',},
    {'name': 'Text Form',
     "notification": 'text',},
]